tabs:
  content:
    sections:
      # info:
      #   type: fields
      #   fields:
      #     info:
      #       label: Info
      #       type: info
      #       text: |
      #         Wenn Inhalte aktualisiert werden, können diese über den Button "Seite deployen" rechts oben veröffentlicht werden. Nach ca. einer Minute sind die aktualisierten Inhalte dann auf der Webseite sichtbar.
      pages:
        type: pages
        layout: table
        label: Menu-Pages
        image: false
        width: 1/3
        create:
          - participants
        templates:
          - venues
          - program
          - about
          - home
          - participants

      footer:
        type: pages
        create: text
        width: 1/3
        label: Footer-Pages
        layout: table
        image: false
        templates:
          - text

  seo: sections/seo
